name: Build & upload luajit bins

on:
  workflow_dispatch:
  push:
    branches: [ "v2.1" ]

permissions:
  contents: read

jobs:
  make-release:
    permissions: write-all
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build Release
        run: |
          cd src
          .\msvcbuild.bat static

      - name: Release Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: bins
          files: |
            src/luajit.lib
            src/lua51.lib

      - name: Build Debug
        run: |
          cd src
          .\msvcbuild.bat debug static

      - name: Release Debug
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: debug_bins
          files: |
            src/luajit.lib
            src/lua51.lib
